# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd $ANDROID_ROOT; rpm/helpers/add_new_device.sh

Description: Pattern with packages for falcon configurations
Name: jolla-configuration-falcon
Requires:
- pattern:jolla-hw-adaptation-falcon
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration falcon

